camel.component.kamelet.location=classpath:kamelets
app.operation=start
app.host=dns:///temporal-frontend.camel-k-temporal-e2e.svc.cluster.local:7233
app.port=7233
app.namespace=default
app.taskQueue=greetings
app.workflowType=GreetingWorkflow
app.workflowExecutionTimeoutSeconds=60
app.workflowId=
app.queryType=getStatus
app.signalName=approve
app.payload=Alice
app.signalPayload=manager-kamelk
